---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role lets_encrypt
# 


LETS_ENCRYPT_DOMAINS: []
LETS_ENCRYPT_EMAIL: !!null

#
# OS packages
#
lets_encrypt_debian_pkgs: ['git', 'bc']

#
# Let's Encrypt
#
lets_encrypt_git_repo: https://github.com/certbot/certbot.git
lets_encrypt_dir: /opt/letsencrypt

#
# nginx
#
let_encrypt_nginx_user: www-data
let_encrypt_nginx_group: www-data
lets_encrypt_nginx_root: /usr/share/nginx/www/
lets_encrypt_challange_dir: '{{lets_encrypt_nginx_root}}/.well-known'
