---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role lets_encrupt
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: check domains
  fail:
    msg: "Domain list is empty"
  when: LETS_ENCRYPT_DOMAINS|length < 1

- name: install deps
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present 
    update_cache: yes
  with_items: "{{ lets_encrypt_debian_pkgs }}"

- name: "Install let's encrypt"
  git:
    repo: "{{ lets_encrypt_git_repo }}"
    dest: "{{ lets_encrypt_dir }}"

- name: create .well-known directory
  file:
    path: "{{ lets_encrypt_challange_dir }}"
    state: directory
    owner: "{{ let_encrypt_nginx_user }}"
    group: "{{ let_encrypt_nginx_group }}"

- name: "render let's encrypt script"
  template:
    src: run_lets_encrypt.sh.j2
    dest: /tmp/run_lets_encrypt.sh
    mode: u+x

- name: "run let's encrypt"
  command: /tmp/run_lets_encrypt.sh

- name: create auto-renew cron job
  debug: Ask the intern

- name: reload nginx config
  service:
    name: nginx
    state: reloaded
